"""add participants.invite_code

The Participant ORM model has carried an `invite_code` column since the
initial schema, but it was missing from the autogenerated initial migration.
Tests pass because they use `Base.metadata.create_all`, but real alembic
deployments are missing the column — `SELECT participants.invite_code` 500s.

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2026-05-14 00:10:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


revision: str = "b2c3d4e5f6a7"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("participants", schema=None) as batch_op:
        batch_op.add_column(sa.Column("invite_code", sa.String(), nullable=True))
        batch_op.create_index(
            "ix_participants_invite_code", ["invite_code"], unique=True
        )


def downgrade() -> None:
    with op.batch_alter_table("participants", schema=None) as batch_op:
        batch_op.drop_index("ix_participants_invite_code")
        batch_op.drop_column("invite_code")
